# Goal position:
trajectory_msgs/JointTrajectory waypoints
bool use_wp_times
int16 wp_type

# Waypoint types
int16 JOINT_SPACE = 0
int16 CARTESIAN_SPACE = 1

# Optionally, set a color when doing the move; otherwise, clear the color.
bool set_color
uint8 r
uint8 g
uint8 b
---
bool success
---
float64 percent_complete
